### ISSUE TITLE
I wonder if there is a way to write this with 3 or less selectors.

### ISSUE THREAD

**Issue by Jieiku** [rilwis/bamboo#2]
https://github.com/rilwis/bamboo/blob/6311e4f486f8b607e5aab6937aa08a99826876b7/src/core.scss#L256

It appears the purpose of this rule is to make input boxes full width if a size is not specified, am I correct?

This rule gets flagged by yellow labs tools for using too many selectors. (anything with more than 3 selectors gets flagged)

I checked modern normalize and sanitize and did not see this rule there, or I would have opened the issue upstream.

Thanks for bamboo!

**Comment by rilwis** [comment]
That's right. The selector targets all inputs except button, submit, reset, checkbox & radio. We set these inputs 100% width by default. It's opinionated and is not in normalize.css or sanitize.css.

Without this selector, we can achieve similar things by writing other input types explicitly, like text, number, search, datetime, date, etc. which I think is longer.

**Comment by Jieiku** [comment]
ah ok, thank you. I will try by setting text, number, search, datetime, date with those.

I can use a comma instead of a string of :not so it should not count as so many selectors it may be a little larger of a file but would be under 3 selectors.

**Comment by rilwis** [comment]
After thinking more about this, I think selecting inputs explicitly is better than nagatively ignore some of them. I've added it in a recent commit.
